// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	BookingID int64            `db:"booking_id" json:"booking_id"`
	ClientID  *int64           `db:"client_id" json:"client_id"`
	ServiceID *int64           `db:"service_id" json:"service_id"`
	Status    string           `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Service struct {
	ServiceID           int64            `db:"service_id" json:"service_id"`
	Name                string           `db:"name" json:"name"`
	Description         *string          `db:"description" json:"description"`
	Category            *string          `db:"category" json:"category"`
	PreviewImageUrl     *string          `db:"preview_image_url" json:"preview_image_url"`
	BasePrice           float64          `db:"base_price" json:"base_price"`
	TherapistCommission *float64         `db:"therapist_commission" json:"therapist_commission"`
	DurationMinutes     int32            `db:"duration_minutes" json:"duration_minutes"`
	IsActive            *bool            `db:"is_active" json:"is_active"`
	DeletedAt           pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt           pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
