// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"context"
)

type Querier interface {
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	GetServiceByID(ctx context.Context, serviceID int64) (Service, error)
	GetServicesByIDs(ctx context.Context, serviceIds []int64) ([]Service, error)
	ListActiveServices(ctx context.Context) ([]Service, error)
	ListPopularServices(ctx context.Context) ([]ListPopularServicesRow, error)
	ListRecentServicesByUser(ctx context.Context, clientID int64) ([]ListRecentServicesByUserRow, error)
	ListUnavailableServices(ctx context.Context) ([]Service, error)
	SoftDeleteService(ctx context.Context, serviceID int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
