// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package dbsqlc

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    name,
    description,
    base_price,
    duration_minutes,
    category,
    is_active,
    preview_image_url,
    therapist_commission,
    subtitle,
    is_featured,
    featured_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING service_id, name, description, category, preview_image_url, base_price, therapist_commission, duration_minutes, is_active, deleted_at, created_at, updated_at, subtitle, is_featured, featured_order
`

type CreateServiceParams struct {
	Name                string   `db:"name" json:"name"`
	Description         *string  `db:"description" json:"description"`
	BasePrice           float64  `db:"base_price" json:"base_price"`
	DurationMinutes     int32    `db:"duration_minutes" json:"duration_minutes"`
	Category            *string  `db:"category" json:"category"`
	IsActive            *bool    `db:"is_active" json:"is_active"`
	PreviewImageUrl     *string  `db:"preview_image_url" json:"preview_image_url"`
	TherapistCommission *float64 `db:"therapist_commission" json:"therapist_commission"`
	Subtitle            *string  `db:"subtitle" json:"subtitle"`
	IsFeatured          bool     `db:"is_featured" json:"is_featured"`
	FeaturedOrder       int32    `db:"featured_order" json:"featured_order"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.DurationMinutes,
		arg.Category,
		arg.IsActive,
		arg.PreviewImageUrl,
		arg.TherapistCommission,
		arg.Subtitle,
		arg.IsFeatured,
		arg.FeaturedOrder,
	)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.PreviewImageUrl,
		&i.BasePrice,
		&i.TherapistCommission,
		&i.DurationMinutes,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subtitle,
		&i.IsFeatured,
		&i.FeaturedOrder,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT service_id, name, description, category, preview_image_url, base_price, therapist_commission, duration_minutes, is_active, deleted_at, created_at, updated_at, subtitle, is_featured, featured_order
FROM services
WHERE service_id = $1::bigint
  AND deleted_at IS NULL
`

func (q *Queries) GetServiceByID(ctx context.Context, serviceID int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, serviceID)
	var i Service
	err := row.Scan(
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.PreviewImageUrl,
		&i.BasePrice,
		&i.TherapistCommission,
		&i.DurationMinutes,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subtitle,
		&i.IsFeatured,
		&i.FeaturedOrder,
	)
	return i, err
}

const getServicesByIDs = `-- name: GetServicesByIDs :many
SELECT service_id, name, description, category, preview_image_url, base_price, therapist_commission, duration_minutes, is_active, deleted_at, created_at, updated_at, subtitle, is_featured, featured_order
FROM services
WHERE service_id = ANY($1::bigint[])
  AND deleted_at IS NULL
`

func (q *Queries) GetServicesByIDs(ctx context.Context, serviceIds []int64) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServicesByIDs, serviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.PreviewImageUrl,
			&i.BasePrice,
			&i.TherapistCommission,
			&i.DurationMinutes,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.IsFeatured,
			&i.FeaturedOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT service_id, name, description, category, preview_image_url, base_price, therapist_commission, duration_minutes, is_active, deleted_at, created_at, updated_at, subtitle, is_featured, featured_order
FROM services
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.PreviewImageUrl,
			&i.BasePrice,
			&i.TherapistCommission,
			&i.DurationMinutes,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.IsFeatured,
			&i.FeaturedOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularServices = `-- name: ListPopularServices :many
SELECT s.service_id, s.name, s.description, s.category, s.preview_image_url, s.base_price, s.therapist_commission, s.duration_minutes, s.is_active, s.deleted_at, s.created_at, s.updated_at, s.subtitle, s.is_featured, s.featured_order
FROM services s
INNER JOIN bookings b ON b.service_id = s.service_id
WHERE s.deleted_at IS NULL
  AND s.is_active = TRUE
  AND b.status = 'completed'
  AND b.created_at > NOW() - INTERVAL '30 days'
GROUP BY
    s.service_id,
    s.name,
    s.description,
    s.base_price,
    s.duration_minutes,
    s.category,
    s.is_active,
    s.preview_image_url,
    s.therapist_commission,
    s.subtitle,
    s.is_featured,
    s.featured_order,
    s.deleted_at,
    s.created_at,
    s.updated_at
ORDER BY COUNT(b.booking_id) DESC
LIMIT 3
`

type ListPopularServicesRow struct {
	Service Service `db:"service" json:"service"`
}

func (q *Queries) ListPopularServices(ctx context.Context) ([]ListPopularServicesRow, error) {
	rows, err := q.db.Query(ctx, listPopularServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularServicesRow{}
	for rows.Next() {
		var i ListPopularServicesRow
		if err := rows.Scan(
			&i.Service.ServiceID,
			&i.Service.Name,
			&i.Service.Description,
			&i.Service.Category,
			&i.Service.PreviewImageUrl,
			&i.Service.BasePrice,
			&i.Service.TherapistCommission,
			&i.Service.DurationMinutes,
			&i.Service.IsActive,
			&i.Service.DeletedAt,
			&i.Service.CreatedAt,
			&i.Service.UpdatedAt,
			&i.Service.Subtitle,
			&i.Service.IsFeatured,
			&i.Service.FeaturedOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentServicesByUser = `-- name: ListRecentServicesByUser :many
SELECT s.service_id, s.name, s.description, s.category, s.preview_image_url, s.base_price, s.therapist_commission, s.duration_minutes, s.is_active, s.deleted_at, s.created_at, s.updated_at, s.subtitle, s.is_featured, s.featured_order
FROM services s
INNER JOIN (
    SELECT service_id, MAX(created_at) AS last_booked
    FROM bookings
    WHERE client_id = $1::bigint
    GROUP BY service_id
) latest_b ON s.service_id = latest_b.service_id
WHERE s.deleted_at IS NULL
  AND latest_b.last_booked > NOW() - INTERVAL '30 days'
ORDER BY latest_b.last_booked DESC
LIMIT 3
`

type ListRecentServicesByUserRow struct {
	Service Service `db:"service" json:"service"`
}

func (q *Queries) ListRecentServicesByUser(ctx context.Context, clientID int64) ([]ListRecentServicesByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecentServicesByUser, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentServicesByUserRow{}
	for rows.Next() {
		var i ListRecentServicesByUserRow
		if err := rows.Scan(
			&i.Service.ServiceID,
			&i.Service.Name,
			&i.Service.Description,
			&i.Service.Category,
			&i.Service.PreviewImageUrl,
			&i.Service.BasePrice,
			&i.Service.TherapistCommission,
			&i.Service.DurationMinutes,
			&i.Service.IsActive,
			&i.Service.DeletedAt,
			&i.Service.CreatedAt,
			&i.Service.UpdatedAt,
			&i.Service.Subtitle,
			&i.Service.IsFeatured,
			&i.Service.FeaturedOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnavailableServices = `-- name: ListUnavailableServices :many
SELECT service_id, name, description, category, preview_image_url, base_price, therapist_commission, duration_minutes, is_active, deleted_at, created_at, updated_at, subtitle, is_featured, featured_order
FROM services
WHERE is_active = FALSE
  AND deleted_at IS NULL
ORDER BY name ASC
LIMIT 3
`

func (q *Queries) ListUnavailableServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listUnavailableServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.PreviewImageUrl,
			&i.BasePrice,
			&i.TherapistCommission,
			&i.DurationMinutes,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.IsFeatured,
			&i.FeaturedOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteService = `-- name: SoftDeleteService :execrows
UPDATE services
SET deleted_at = CURRENT_TIMESTAMP
WHERE service_id = $1::bigint
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteService(ctx context.Context, serviceID int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteService, serviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
